address = "0.0.0.0:8022"

[ssh]
banner = "Welcome to Vlab\n"
handshake-timeout-seconds = 30
upstream-timeout-seconds = 30
host-keys = [
    { path = "/tmp/sshmux/ssh_host_ed25519_key" },
    { path = "/tmp/sshmux/ssh_host_ecdsa_key" },
    { path = "/tmp/sshmux/ssh_host_rsa_key" },
]

[auth]
endpoint = "http://127.0.0.1:5000/ssh"
version = "legacy"
timeout-seconds = 30
# Legacy settings
token = "token"
all-username-nopassword = true
usernames-nopassword = ["vlab", "ubuntu", "root"]
invalid-usernames = ["用户名"]
invalid-username-message = "Invalid username %s. Please check https://vlab.ustc.edu.cn/docs/login/ssh/#username for more information."

[logger]
enabled = true
endpoint = "udp://127.0.0.1:5556"

[metrics]
enabled = true
service-name = "sshmux"
interval-seconds = 60
attributes = [
    { name = "deployment.environment.name", value = "production" },
]
connection-grouping = false

[metrics.otlp]
enabled = true
protocol = "http"
endpoint = "http://127.0.0.1:4318/v1/metrics"
timeout-seconds = 10
headers = [
    { name = "Authorization", value = "ApiKey 12345678" },
]

[metrics.prometheus]
enabled = true
address = "127.0.0.1:9100"
path = "/metrics"

[tracer]
enabled = true
service-name = "sshmux"
sample-ratio = 0.25
propagation = true

[tracer.otlp]
enabled = true
protocol = "grpc"
endpoint = "http://127.0.0.1:4317"

[proxy-protocol]
enabled = true
hosts = ["127.0.0.22"]

[recovery]
address = "172.30.0.101:2222"
usernames = ["recovery", "console", "serial"]
token = "token"
