address = "0.0.0.0:8022"

[ssh]
banner = "Welcome to Vlab\n"
host-keys = [
    "/tmp/sshmux/ssh_host_ed25519_key",
    "/tmp/sshmux/ssh_host_ecdsa_key",
    "/tmp/sshmux/ssh_host_rsa_key",
]

[auth]
endpoint = "http://127.0.0.1:5000/ssh"
token = "token"
# Legacy settings
all-username-nopassword = true
usernames-nopassword = ["vlab", "ubuntu", "root"]
invalid-usernames = ["用户名"]
invalid-username-message = "Invalid username %s. Please check https://vlab.ustc.edu.cn/docs/login/ssh/#username for more information."

[logger]
enabled = true
endpoint = "udp://127.0.0.1:5556"

[proxy-protocol]
enabled = true
networks = ["127.0.0.22/32"]

[recovery]
address = "172.30.0.101:2222"
usernames = ["recovery", "console", "serial"]
token = "token"
